In [1]:
print ("Hello World")

Hello World


In [4]:
#Create a 1D array
import numpy as np
arr = ([1,2,3,4,5])
print(arr)

[1, 2, 3, 4, 5]


In [5]:
#Create a 2D array
import numpy as np
arr = ([1,2,3],
       [4,5,6])
print(arr)

([1, 2, 3], [4, 5, 6])


In [11]:
#Create an array of zeros
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#Create an array of ones
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#Create a range array
r=np.arange(0,10,2)
print(r)

[0 2 4 6 8]


In [15]:
#Random array
rand=np.random.rand(1,3)
print(rand)

[[0.84435953 0.70347088 0.13369212]]


In [18]:
#Arithmetic operations
a=np.array([1,3,2])
b=np.array([4,6,5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 9 7]
[-3 -3 -3]
[ 4 18 10]
[0.25 0.5  0.4 ]


In [19]:
#Max,Min,Sum
arr=np.array([10,20,5,15])
print(arr.max())
print(arr.min())
print(arr.sum())

20
5
50


In [20]:
#Slicing
arr=np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]
